name: Manual Sync from GitLab (Exclude .github)
on:
  workflow_dispatch:  # 仅手动触发

permissions:
  contents: write    # 允许修改代码
  actions: write     # 允许操作工作流文件（删除需要此权限）

jobs:
  sync-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub 仓库
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0  # 必须获取完整历史

      - name: 添加并拉取 GitLab 仓库
        run: |
          git remote add gitlab https://git.ryujinx.app/ryubing/ryujinx.git
          git fetch gitlab master

      - name: 合并 GitLab 更新
        run: |
          git config --global user.name "GitHub Actions Sync Bot"
          git config --global user.email "actions@github.com"
          git merge --no-edit gitlab/master --allow-unrelated-histories

      - name: 强制保留 GitHub 的 .github 目录（关键步骤）
        run: |
          # 恢复 GitHub 原有的 .github 目录（覆盖 GitLab 的更改）
          git checkout origin/master -- .github
          git add .github
          git commit -m "chore: retain GitHub's .github directory"

      - name: 推送更新到 GitHub
        run: git push origin master
