name: Manual Sync from GitLab
on:
  workflow_dispatch:  # 仅手动触发

# 关键修复点：使用正确的权限名称
permissions:
  contents: write    # 允许修改代码
  actions: write     # 允许修改工作流文件（原 workflows: write 是无效的）

jobs:
  sync-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub 仓库
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: 添加并拉取 GitLab 仓库
        run: |
          git remote add gitlab https://git.ryujinx.app/ryubing/ryujinx.git
          git fetch gitlab master

      - name: 合并并推送更新
        run: |
          git config --global user.name "GitHub Actions Sync Bot"
          git config --global user.email "actions@github.com"
          git merge --no-edit gitlab/master --allow-unrelated-histories
          git push origin master
