name: Manual Sync from GitLab (Exclude Canary)
on:
  workflow_dispatch:  # 仅手动触发

permissions:
  contents: write    # 允许修改代码
  actions: write     # 允许修改工作流文件（即使要删除也需要此权限）

jobs:
  sync-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub 仓库
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: 添加并拉取 GitLab 仓库
        run: |
          git remote add gitlab https://git.ryujinx.app/ryubing/ryujinx.git
          git fetch gitlab master

      - name: 合并 GitLab 更新
        run: |
          git config --global user.name "GitHub Actions Sync Bot"
          git config --global user.email "actions@github.com"
          git merge --no-edit gitlab/master --allow-unrelated-histories

      - name: 删除 Canary 工作流文件（关键步骤）
        run: |
          # 删除文件并提交
          git rm --force .github/workflows/canary.yml
          git commit -m "chore: exclude canary.yml from sync"

      - name: 推送更新到 GitHub
        run: git push origin master
